### ISSUE TITLE
Simpleassets filler crashes at various steps

### ISSUE THREAD

**Issue by hanar3** [pinknetworkx/eosio-contract-api#10]
Hi -- I'm using eosio-contract-api to sync with the simpleassets contract and I stumbled upon some issues running the filler.

Sorry about the long list and thanks for taking the time to look into this!
Here's a list of what I've found, below there's also the steps to reproduce.

1. simpleassets.sql file throws during the queries execution
    - simpleassets_authors specifies the constraint `CONSTRAINT simpleassets_collections_pkey PRIMARY KEY (contract, collection_name)`, but the table itself does not create a field called `collection_name` which makes the query throw. This is also inconsistent with the simpleassets contract, which doesn't have collections as part of the contract specification.
    - On line 70 and 71 there's two indexes being created with the same name, also makes the query throw.
  
2. `definitions/migrations/1.2.3/database.sql` throws `multiple primary keys for table "contract_traces" are not allowed`

3. Under `filler/handlers/simpleassets/index.ts`, line 90.
   - This line throws with the following error: `INSERT has more expressions than target columns` removing the $3 on the query seems to fix the issue.

4. Under `filler/handlers/simpleassets/processors/assets.ts`, line 30.
   - `assetid` is mistyped as `asseetid`, this also makes the query throw because we expect a non-null value for asset_id inside the db.

5. This is the last one I've found, also under `filler/handlers/simpleassets/processors/assets.ts`
    - Under the `claim` action, the query expects three variables but there's only two being passed, removing the `AND owner = $3` seems to fix the issue.

This is my readers.json:

<details>
  <summary>readers.json</summary>
  
```json
[
  {
    "name": "simple-1",

    "start_block":  12324528,
    "stop_block": 0,
    "irreversible_only": false,

    "ship_prefetch_blocks": 50,
    "ship_min_block_confirmation": 30,
    "ship_ds_queue_size": 20,

    "db_group_blocks": 10,

    "ds_ship_threads": 4,

    "modules": [],

    "contracts": [
      {
        "handler": "simpleassets",
        "args": {
          "simpleassets_account": "simpleassets",
          "store_transfers": true,
          "store_logs": true
        }
      },
      {
        "handler": "delphioracle",
        "args": {
          "delphioracle_account": "delphioracle"
        }
      }
    ]
  }
]


```
</details>

Steps to reproduce: 
 1. run `yarn start:filler` with the above readers.json and see the errors happen

**Comment by fabian-emilius** [comment]
SimpleAssets filler is not tested at all at the moment. 

Thanks for the detailed info and I pushed a fix for your issues
