### ISSUE TITLE
Is there a way to know what collections are whitelisted/verified?

### ISSUE THREAD

**Issue by DrSoops** [pinknetworkx/eosio-contract-api#12]
I want to make a notification service for my discord server to automatically notify my community about important drops.
Looking at the API I could not figure out a way to tell if a collection is verified or whitelisted or if it is a potential scam.

Is there a way to get this information through an api and not just through a browser and looking for the checkmarks?

**Comment by fabian-emilius** [comment]
No, this is not saved within the API and you need to use external sources
