### ISSUE TITLE
 Unhandled error request to http://127.0.0.1:8888/v1/chain/get_info failed, reason: connect ECONNREFUSED 127.0.0.1:8888

### ISSUE THREAD

**Issue by soroka41** [pinknetworkx/eosio-contract-api#20]
Unhandled error request to http://127.0.0.1:8888/v1/chain/get_info failed, reason: connect ECONNREFUSED 127.0.0.1:8888

**Comment by fabian-emilius** [comment]
This means that you are not running a blockchain node on that host + port
