### ISSUE TITLE
Response returned with this_block is always null

### ISSUE THREAD

**Issue by peter-phamn** [pinknetworkx/eosio-contract-api#32]
I have started the project, I use nodeos from WAX testnet. Everything is fine, but the following response with this_block is always null. Can you help me? (my start_block = 0 )

**Comment by fabian-emilius** [comment]
you probably started node from a snapshot. If not then try setting start_block to 2 but in current versions this should be fixed

**Comment by Ahmedpooh** [comment]
> I have started the project, I use nodeos from WAX testnet. Everything is fine, but the following response with this_block is always null. Can you help me? (my start_block = 0 )

I,m interested 
Can u contact me?
