### ISSUE TITLE
Running api without local node

### ISSUE THREAD

**Issue by Dewald928** [pinknetworkx/eosio-contract-api#65]
I'm trying to eventually run this API for the Telos testnet and mainnet, but I am a bit stuck.

### My first attempt at connecting to wax testnet
I used the default settings for all the config files. I just changed the `start_block` to 35795000
And I changed the connections such that

```
"postgres": {
    "host": "eosio-contract-api-postgres",
    "port": 5432,
    "user": "root",
    "password": "changeme",
    "database": "root"
  },
  "redis": {
    "host": "eosio-contract-api-redis",
    "port": 6379
  },
  "chain": {
    "name": "wax-testnet",
    "chain_id": "f16b1833c747c43682f4386fca9cbb327929334a762755ebec17f6f23c9b8a12",
    "http": "https://testnet.wax.pink.gg",
    "ship": "wss://testnet.wax.pink.gg"
  }
```

Then I ran `docker-compose up -d`
I got the same issue in the filler as #51 (`No blocks processed [DS:0|SH:0|JQ:0]`)

**My first question is:** Is it okay to point to another endpoint with state history like this? Does that endpoint even have state-history? I just assumed it would, how can I know?

**Secondly:** I had to change the host to the docker container names or else it won't connect. Is there a better way to do this? If it's localhost then the `yarn test` works, but if it is like above, then it fails. I'm sure this is just docker things I don't understand yet? 

Thanks

**Comment by fabian-emilius** [comment]
State history usually is not exposed publicly because its an internal API, so you need to host your own node or ask someone for a private connection. You need to start at a block that is before atomicassets and atomicmarket were deployed to the chain

**Comment by Dewald928** [comment]
I see. Thanks a bunch. 
I'll close for now.
